### ISSUE TITLE
Package linting issues

### ISSUE THREAD

**Issue by protesilaos** [aadcg/emacs-yeis#1]
Hi @aadcg! Thank you for this package.  You would benefit in your dev work by using a linter for Emacs packaging conventions.

This is a possible way to go, depending on whether you use those front-ends.

```elisp
(use-package flycheck-package
  :ensure
  :after flycheck
  :config
  (flycheck-package-setup))

(use-package package-lint-flymake
  :ensure
  :after flymake
  :config
  (package-lint-flymake-setup))
```

**Comment by aadcg** [comment]
Hi @protesilaos! Thank your for providing me a ready linter configuration from which yeis will definitely benefit. 

I'm wondering if have seen something in the elisp code that caught your attention or if this is just a general recommendation. 

I have run the linting tool and have made some corrections (check the latest commit).

**Comment by protesilaos** [comment]
It was just for the general feedback the linter gives.

**Comment by aadcg** [comment]
Thanks again. Closing the issue.

**Comment by protesilaos** [comment]
You are welcome!
